In [111]:
import pandas as pd 
import numpy as np 
import extract_vector as ev

In [112]:
train_data_wavelet = ev.getWaveletData(type='eeg')
train_arousal = ev.getLabelData(type='arousal')
train_valence = ev.getLabelData(type='valence')

In [113]:
def clean_train_data(train_data, train_label):
    """
    Input: train_data,train_label 
    Ouput: train_data,train_label 
           updated train data and updated train label after removing the nan rows
    """
    n = train_data.shape[0]
    m = train_data.shape[1]
    nan_ll = []
    for i in range(n):
        if(np.isnan(np.sum(train_data[i:i+1, :]))):
            nan_ll.append(i)

    train_data = np.delete(train_data, nan_ll, 0)
    train_label = np.delete(train_label, nan_ll, 0)
    return train_data, train_label

In [114]:
train_label = np.concatenate((train_arousal,train_valence),axis = 1)

In [115]:
train_data_wavelet,train_label = clean_train_data(train_data_wavelet,train_label)

In [116]:
valence_labels=train_label[:,0]

In [117]:
arousal_labels=train_label[:,1]

#### Rounding the valence and arousal values..

In [118]:
valence_labels = [round(x) for x in valence_labels]

In [119]:
arousal_labels = [round(x) for x in arousal_labels]

In [120]:
from sklearn.model_selection import train_test_split

In [199]:
X_train,X_test,Y_train,Y_test= train_test_split(train_data_wavelet,valence_labels,test_size=0.2, random_state=42)

In [200]:
train_data_wavelet

array([[  5.476139 ,   9.865373 ,  19.332855 , ...,  46.63191  ,
        108.83272  , 320.056    ],
       [  9.781198 ,  17.070133 ,  22.27329  , ...,  32.223095 ,
         77.85503  , 207.98218  ],
       [  6.585784 ,  12.16199  ,  19.33303  , ...,  30.543392 ,
        108.4805   , 234.14474  ],
       ...,
       [  5.0930405,  15.621225 ,  87.65114  , ...,  15.319633 ,
         35.56466  ,  72.37201  ],
       [  2.3521676,   5.2113194,   9.408207 , ...,  11.014575 ,
         26.782963 ,  51.938957 ],
       [  3.4392505,   6.8724422,   9.679507 , ...,  11.619453 ,
         31.718126 ,  58.873123 ]], dtype=float32)

In [201]:
X_train[0]

array([  8.255108 ,  17.30702  ,  25.542423 ,  64.410965 , 151.8081   ,
         3.429237 ,   6.189559 ,   7.1442614,  12.475449 ,  23.90936  ,
         3.0555964,   6.0238514,   7.1471496,  12.397403 ,  21.723457 ,
         6.5330267,  13.70317  ,  17.353132 ,  27.203588 ,  42.076466 ,
         8.974438 ,  16.070883 ,  13.273225 ,  13.537489 ,  28.119148 ,
         3.670201 ,   6.675373 ,   7.3274527,  11.699961 ,  21.641933 ,
         2.737173 ,   5.08     ,   6.777829 ,  11.92624  ,  21.582716 ,
         2.532916 ,   4.883307 ,   7.575052 ,  13.665888 ,  24.347214 ,
         4.0970902,   7.401099 ,   8.4678545,  13.513396 ,  23.722416 ,
         4.7104692,   8.774324 ,   9.201374 ,  15.265851 ,  33.283928 ,
         6.09216  ,  11.078029 ,   9.331462 ,  11.493164 ,  21.032114 ,
         3.4695098,   6.695778 ,   6.9656525,  11.38035  ,  20.827316 ,
         3.04596  ,   5.370727 ,   6.31879  ,  12.607085 ,  27.089514 ,
         3.9366722,   7.901394 ,  11.186843 ,  33.786026 ,  88.3

In [124]:
from sklearn import svm
from sklearn.metrics import accuracy_score

In [125]:
clasf=svm.SVC()

In [208]:
clasf.fit(X_train,Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [209]:
predictions = clasf.predict(X_test)

In [210]:
print(accuracy_score(Y_test, predictions))

0.2052980132450331


In [129]:
X_train1,X_test1,Y_train1,Y_test1= train_test_split(train_data_wavelet,arousal_labels,test_size=0.2, random_state=42)

In [130]:
clasf1=svm.SVC()

In [131]:
clasf1.fit(X_train1,Y_train1)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [132]:
predictions1 = clasf1.predict(X_test1)

In [133]:
print(accuracy_score(Y_test1, predictions1))

0.17880794701986755


In [134]:
train_data_fourier = ev.getFourierData(type='eeg')

In [135]:
train_data_fourier,train_label = clean_train_data(train_data_fourier,train_label)

In [136]:
X_train2,X_test2,Y_train2,Y_test2= train_test_split(train_data_fourier,valence_labels,test_size=0.2, random_state=42)

In [137]:
clasf2=svm.SVC()

In [138]:
clasf2.fit(X_train2,Y_train2)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [139]:
predictions2= clasf2.predict(X_test2)

In [140]:
print(accuracy_score(Y_test2, predictions2))

0.2251655629139073


In [141]:
predictions2

array([6., 6., 6., 7., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 5., 6., 6., 6., 6.,
       6., 6., 6., 6., 7., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 7., 6., 6., 6., 6., 6., 6., 6., 6., 7., 6., 6., 6., 6.,
       7., 7., 6., 6., 5., 6., 6., 5., 6., 6., 7., 6., 6., 6., 6., 6., 7.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 7., 6., 7.,
       6., 6., 6., 6., 6., 6., 6., 5., 6., 6., 6., 6., 6., 7., 6., 6., 6.,
       6., 6., 6., 6., 5., 6., 7., 6., 6., 7., 6., 6., 6., 6., 6., 7., 6.,
       6., 6., 6., 7., 7., 6., 6., 7., 6., 6., 6., 6., 6., 6., 6.])