In [1]:
import pandas as pd 
import numpy as np 
import extract_vector as ev
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit

In [2]:
def clean_train_data(train_data, train_label):
    """
    Input: train_data,train_label 
    Ouput: train_data,train_label 
           updated train data and updated train label after removing the nan rows
    """
    n = train_data.shape[0]
    m = train_data.shape[1]
    nan_ll = []
    for i in range(n):
        if(np.isnan(np.sum(train_data[i:i+1, :]))):
            nan_ll.append(i)

    train_data = np.delete(train_data, nan_ll, 0)
    train_label = np.delete(train_label, nan_ll, 0)
    return train_data, train_label

In [3]:
def get_train_labels(train_label):
    for i in train_label:
        if(i[0] > 4.5):
            i[0] = 1
        else:
            i[0] = 0

        if(i[1] > 4.5):
            i[1] = 1
        else:
            i[1] = 0
    return train_label

In [4]:
cv = ShuffleSplit(n_splits=5,test_size=0.3,random_state=42)

### Wavelet Entropy Model

In [5]:
train_data = ev.getWaveletEntropyData()
train_label = ev.getLabelData(type='ValAr')

In [6]:
train_data,train_label = clean_train_data(train_data,train_label)
train_label = get_train_labels(train_label)

In [7]:
x_train,x_test,y_train,y_test = train_test_split(train_data,train_label,test_size = 0.2,random_state = 42)

#### Arousal

In [8]:
cross_val_score(SVC(),train_data,train_label[:,0],scoring='accuracy',cv=cv)

array([0.72687225, 0.72687225, 0.70044053, 0.69162996, 0.71365639])

In [9]:
arousal_model = SVC()

In [10]:
arousal_model.fit(x_train,y_train[:,0])

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [11]:
pred = arousal_model.predict(x_test)

In [12]:
print(classification_report(pred,y_test[:,0]))

              precision    recall  f1-score   support

         0.0       0.20      0.77      0.32        13
         1.0       0.97      0.71      0.82       138

    accuracy                           0.72       151
   macro avg       0.59      0.74      0.57       151
weighted avg       0.90      0.72      0.78       151



In [13]:
print(accuracy_score(pred,y_test[:,0]))

0.7152317880794702


#### Valence

In [14]:
cross_val_score(SVC(),train_data,train_label[:,1],scoring='accuracy',cv=cv)

array([0.63876652, 0.59030837, 0.63876652, 0.6123348 , 0.6123348 ])

In [15]:
valence_model = SVC()

In [16]:
valence_model.fit(x_train,y_train[:,1])

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [17]:
pred = valence_model.predict(x_test)

In [18]:
print(classification_report(pred,y_test[:,1]))

              precision    recall  f1-score   support

         0.0       0.22      0.40      0.29        30
         1.0       0.81      0.65      0.72       121

    accuracy                           0.60       151
   macro avg       0.52      0.53      0.51       151
weighted avg       0.70      0.60      0.64       151



In [19]:
print(accuracy_score(pred,y_test[:,1]))

0.6026490066225165


### Fourier Entropy Model

In [20]:
train_data = ev.getFourierEntropyData()
train_label = ev.getLabelData(type='ValAr')

In [21]:
train_data,train_label = clean_train_data(train_data,train_label)
train_label = get_train_labels(train_label)

In [22]:
x_train,x_test,y_train,y_test = train_test_split(train_data,train_label,test_size = 0.2,random_state = 42)

#### Arousal

In [23]:
cross_val_score(SVC(),train_data,train_label[:,0],scoring='accuracy',cv=cv)

array([0.6784141 , 0.66079295, 0.63436123, 0.66519824, 0.69162996])

In [24]:
arousal_model = SVC()

In [25]:
arousal_model.fit(x_train,y_train[:,0])

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [26]:
pred = arousal_model.predict(x_test)

In [27]:
print(classification_report(pred,y_test[:,0]))

              precision    recall  f1-score   support

         0.0       0.04      0.50      0.07         4
         1.0       0.98      0.67      0.80       147

    accuracy                           0.67       151
   macro avg       0.51      0.59      0.44       151
weighted avg       0.96      0.67      0.78       151



In [28]:
print(accuracy_score(pred,y_test[:,0]))

0.6688741721854304


#### Valence

In [29]:
cross_val_score(SVC(),train_data,train_label[:,1],scoring='accuracy',cv=cv)

array([0.66519824, 0.60352423, 0.65638767, 0.6123348 , 0.60792952])

In [30]:
valence_model = SVC()

In [31]:
valence_model.fit(x_train,y_train[:,1])

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [32]:
pred = valence_model.predict(x_test)

In [33]:
print(classification_report(pred,y_test[:,1]))

              precision    recall  f1-score   support

         0.0       0.15      0.57      0.24        14
         1.0       0.94      0.66      0.78       137

    accuracy                           0.66       151
   macro avg       0.54      0.62      0.51       151
weighted avg       0.86      0.66      0.73       151



In [34]:
print(accuracy_score(pred,y_test[:,1]))

0.6556291390728477
